### ISSUE TITLE
Pr2: la función `devSenior` tiene demasiadas responsabilidades

### ISSUE THREAD

**Issue by fidel-ml** [Juan-Insa/EstrD22s1#10]
Al hacer doble PM la estás recargando. Si estás mirando el Rol, no mirás sus componentes, sino que delegás en otras funciones auxiliares que corresponda...

**Comment by Juan-Insa** [comment]
ahora esDevSenior llama a una subtarea 

esDevSenior :: Rol -> Bool
esDevSenior (Developer s _) = esSenior s
esDevSenior _               = False

-- dado un Seniority indica si es Senior.
esSenior :: Seniority -> Bool
esSenior Senior = True
esSenior _         = False
