### ISSUE TITLE
Pr 2: en `cantQueTrabajanEn'` estás mirando AMBOS argumentos, aunque no es necesario 

### ISSUE THREAD

**Issue by fidel-ml** [Juan-Insa/EstrD22s1#11]
Una vez más, NO hay que mirar más de un argumento salvo que sea imprescindible...
En este caso, perdiste la recursión estructural de la técnica Miyagui por tratar de ganar algo que tenías de todas maneras.

**Comment by Juan-Insa** [comment]
nueva solucion:

cantDesarrolladoresEn :: [Rol] -> [Proyecto] -> Int
cantDesarrolladoresEn []     _  = 0
cantDesarrolladoresEn (r:rs) ps = unoSi (trabajaEn r ps) + cantDesarrolladoresEn rs ps
