### ISSUE TITLE
Pr2: en la función `asignadosPorProyecto` estás repitiendo muchas veces cada proyecto...

### ISSUE THREAD

**Issue by fidel-ml** [Juan-Insa/EstrD22s1#12]
O sea, si un proyecto `p` particular aparece 3 veces, ponés 3 elementos `(p,3)` en la lista final, y esto no es feliz.
Además, estás recorriendo muchísimas veces todos los proyectos de la empresa, lo que no es muy bueno.
La idea es usar recursión estructural sobre los proyectos de la empresa...

**Comment by Juan-Insa** [comment]
No entiendo a que te referís :(, la subtarea proyectos ya te da los proyectos de la empresa sin repetidos. A partir de eso hago la recursión en cantPorProyecto. Lo probé con winhugs y no me los repite. 
Lo que puede llegar a pasar es que si hay un desarrollador repetido con un mismo proyecto te los vuelve a contar pero yo supuse que por lógica en la lista de roles de la empresa no hay desarrolladores repetidos al menos que esté en distintos proyectos.

**Comment by fidel-ml** [comment]
Ahhh. Sacás los repetidos. Entonces, lo que estás haciendo es recorrer 200 veces para sacar los repetidos, y después, por cada proyecto, volver a recorrer todo para contar para ese solo... Es MUCHO trabajo de más en forma innecesaria.
La idea es usar recursión estructural... Sale  TAN fácil.
