### ISSUE TITLE
Pr3: `alMenosNTesoros` está incompleta

### ISSUE THREAD

**Issue by fidel-ml** [Juan-Insa/EstrD22s1#14]
Este código no puede ejecutar. NUNCA subas código que no es ejecutable a la rama master de un repo GIT.

**Comment by Juan-Insa** [comment]
se me chispoteo,

`alMenosNTesoros :: Int -> Camino -> Bool
alMenosNTesoros n Fin          = n < 0
alMenosNTesoros n (Nada c)     = n < 0 || alMenosNTesoros n c
alMenosNTesoros n (Cofre os c) = n < 0 || alMenosNTesoros (n-cantDeTesoros os) c


cantDeTesoros :: [Objeto] -> Int
cantDeTesoros []     = 0
cantDeTesoros (o:os) = unoSi (esTesoro o) + cantDeTesoros os`
