### ISSUE TITLE
Pr2: `elMasViejo` no está hecha por recursión estructural

### ISSUE THREAD

**Issue by fidel-ml** [Juan-Insa/EstrD22s1#4]
Mismo esquema que en #3, y no es feliz, porque es complejo de seguir en forma innecesaria

**Comment by Juan-Insa** [comment]
nueva solución:

elMasViejo :: [Persona] -> Persona
elMasViejo (p:[]) = p
elMasViejo (p:ps) = elMasViejoEntre p (elMasViejo ps)
