### ISSUE TITLE
Pr2: Los nombres de funciones con ' no son adecuados

### ISSUE THREAD

**Issue by fidel-ml** [Juan-Insa/EstrD22s1#5]
En general, no es feliz titular a funciones con nombres con '. Lo hacemos cuando queremos mostrar variaciones, pero no para funciones con diferente tipo, por ejemplo. Vos tenés cosas como `cantPokemonDe` y `cantPokemonDe'`, y no se entiende, viendo el nombre, cuál es cuál...

**Comment by Juan-Insa** [comment]
cambié el nombre de todas las funciones con '
