### ISSUE TITLE
Pr 2: en `proyectosSinRepetidos` estás mirando la pertenencia contra una lista más larga de lo necesaria

### ISSUE THREAD

**Issue by fidel-ml** [Juan-Insa/EstrD22s1#9]
Al usar `ps` en lugar de `proyectosSinRepetidos ps` en la condición, mirás más veces de las necesarias.
Esto es en general para cuando querés remover duplicados...

**Comment by Juan-Insa** [comment]
cambié ps por proyectosSinRepetidos ps en la condición.

**Comment by fidel-ml** [comment]
Bien. Ahora estás llamando 2 veces a la recursión... ¿Recordás que este ejercicio lo conversamos en clase?
Pensando con subtareas se evita el problema... ;)

**Comment by Juan-Insa** [comment]
proyectosSinRepetidos :: [Proyecto] -> [Proyecto]
proyectosSinRepetidos []     = []
proyectosSinRepetidos (p:ps) = agregarSiNoEsta p (proyectosSinRepetidos ps)
